---
title: "ADCIRC-EDA"
author: "Brian N. White"
date: "2022-05-11"
output: html_document
---

```{r, include = F}
knitr::opts_chunk$set(fig.align = 'center', warning = F, message = F, tidy=TRUE)
```

```{r, include = F}
# data wrangling & visualization
library(tidyverse) # data science workflow
library(reshape2) # combining data columns
library(gridExtra) # plot multiple ggplots on grid of specified dimension
library(gganimate) # animates ggplot objects
library(gifski) # renders gifs

# extreme value analysis
library(extRemes) # univariate extremes

# working with spatial data
library(maps)
library(ggmap)
library(geosphere)
library(naniar) # for replacing value with NA 
```

```{r import and clean data, warning = F, message = F}
# load data
df_meta_region3 <- read.csv('data/df_meta_region3.csv')

# raw sea levels
ADC_POST_region3 <- read.csv('data/ADC_POST_region3.csv') 
NOAA_OBS_region3 <- read.csv('data/NOAA_OBS_region3.csv')

# detided sea levels
ADC_POST_Detided_region3 <- read.csv('data/ADC_POST_Detided_region3.csv')
NOAA_OBS_Detided_region3 <- read.csv('data/NOAA_OBS_Detided_region3.csv')
```

```{r clean data}
source('./functions/clean_timeseries.R') # converts time to POSIX class, adds variables month & year, replace station ID with station name
source('./functions/clean_metadata.R') # remove white space from station names

df_meta_region3 <- clean_metadata(df_meta_region3) # remove white space from station names

# raw sea levels
ADC_POST_region3 <- clean_timeseries(timeseries = ADC_POST_region3, 
                                             metadata = df_meta_region3 
                                                            %>% filter(stationname != 'Lewisetta')
                                             ) %>%
                                select(1:4, 30:5) %>%
                                select(1:13, 15:14, 16:30)

NOAA_OBS_region3 <- clean_timeseries(timeseries = NOAA_OBS_region3, metadata = df_meta_region3) %>%
                              select(-Lewisetta) %>%
                              select(1:13, 15:14, 16:30) # exclude Lewisetta for consistency with ADCIRC data
                              
# detided sea levels
ADC_POST_Detided_region3 <- clean_timeseries(timeseries = ADC_POST_Detided_region3, 
                                             metadata = df_meta_region3 
                                                            %>% filter(stationname != 'Lewisetta')
                                             ) %>%
                                select(1:13, 15:14, 16:30)

NOAA_OBS_Detided_region3 <- clean_timeseries(timeseries = NOAA_OBS_Detided_region3, metadata = df_meta_region3) %>%
                              select(-Lewisetta) %>% # exclude Lewisetta for consistency with ADCIRC data
                              select(1:4, 30:5) # re-arrange stations to match order of columns in ADC_POST_Detided_region3

df_meta_region3 <- df_meta_region3 %>% 
                          filter(stationname != 'Lewisetta') # remove Lewisetta from meta data
```

*Interactive Map of Stations*

[kepler.gl](https://briannathanwhite.github.io/images/research/reanalysis-heatmap.html)

```{r raw data EDA}
p1a <- ADC_POST_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-01-01 23:00:00') %>% # one day
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue') +
  labs(x = 'Hour', y = 'Sea-level (m)', title = 'ADCIRC Reconstruction of Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

p2a <- NOAA_OBS_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-01-01 23:00:00') %>% # one day
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red') +
  labs(x = 'Hour', y = 'Sea-level (m)', title = 'Observed (NOAA) Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p1a, p2a, ncol = 2)

p3a <- ADC_POST_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>% # one month
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Month', y = 'Sea-level (m)', title = 'ADCIRC Reconstruction of Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

p4a <- NOAA_OBS_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>% # one month
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Month', y = 'Sea-level (m)', title = 'Observed (NOAA) Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p3a, p4a, ncol = 2)

p5a <- ADC_POST_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>% # one year
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Year', y = 'Sea-level (m)', title = 'ADCIRC Reconstruction of Hourly Sea-Level at Wrightsville Beach')  +
  ylim(-2.5, 2.5)

  p5a_n <- ADC_POST_region3 %>% # number of time observations in timeseries
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>%
  nrow()

  play5a <- p5a + transition_reveal(1:p5a_n)
  animate(play5a, height = 400, width = 550)
  anim_save(filename = "hourly-year-ADCIRC-wrighstville.gif", path ='./figures')

p6a <- NOAA_OBS_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>% # one year
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Year', y = 'Sea-level (m)', title = 'Observed (NOAA) Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p5a, p6a)

p7a <- ADC_POST_region3 %>% # complete time-series%
        ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
        geom_point(col = 'blue', size = 0.1) +
        labs(x = 'Year', 
             y = 'Sea-level (m)', 
             title = 'ADCIRC Reconstruction of Hourly Sea-Level at Wrightsville Beach') +
             ylim(-2.5, 2.5)

p8a <- NOAA_OBS_region3 %>% # complete time-series
        ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
        geom_point(col = 'red', size = 0.1) +
        labs(x = 'Year', y = 'Sea-level (m)', title = 'Observed (NOAA) Hourly Sea-Level at Wrightsville Beach') +
        ylim(-2.5, 2.5)

grid.arrange(p7a, p8a, ncol = 2)
```



```{r hourly detided sea-level EDA, cache = T, message = F, warning = F}
# time-series of detided sea-levels
p1 <- ADC_POST_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-01-01 23:00:00') %>% # one day
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue') +
  labs(x = 'Hour', y = 'Detided Sea-level (m)', title = 'ADCIRC Reconstruction of Detided Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

p2 <- NOAA_OBS_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-01-01 23:00:00') %>% # one day
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red') +
  labs(x = 'Hour', y = 'Detided Sea-level (m)', title = 'Observed (NOAA) Detided Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p1, p2, ncol = 2)

grid.arrange(p1a, p2a, p1, p2, nrow = 2, ncol = 2)

p3 <- ADC_POST_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>% # one month
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Month', y = 'Detided Sea-level (m)', title = 'ADCIRC Reconstruction of Detided Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

  p3_n <- ADC_POST_Detided_region3 %>% # number of time observations in timeseries
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>%
  nrow()

  play3 <- p3 + transition_reveal(1:p3_n)
  animate(play3, height = 400, width = 550)
  anim_save(filename = "hourly-month-detided-ADCIRC-wrighstville.gif", path ='./figures')

p4 <- NOAA_OBS_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>% # one month
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Month', y = 'Detided Sea-level (m)', title = 'Observed (NOAA) Detided Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p3, p4, ncol = 2) 

grid.arrange(p3a, p4a, p3, p4, nrow =2, ncol = 2)

p5 <- ADC_POST_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>% # one year
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Year', y = 'Detided Sea-level (m)', title = 'ADCIRC Reconstruction of Detided Hourly Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

  p5_n <- ADC_POST_Detided_region3 %>% # number of time observations in timeseries
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>%
  nrow()

  play5 <- p5 + transition_reveal(1:p5_n)
  animate(play5, height = 400, width = 550)
  anim_save(filename = "hourly-year-detided-ADCIRC-wrighstville.gif", path ='./figures')

p6 <- NOAA_OBS_Detided_region3 %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>% # one year
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Year', y = 'Detided Sea-level (m)', title = 'Observed (NOAA) Detided Hourly Sea-Level at Wrightsville Beach')  +
  ylim(-2.5, 2.5)

grid.arrange(p5, p6, ncol = 2)

grid.arrange(p5a, p6a, p5, p6, nrow = 2, ncol = 2)

p7 <- ADC_POST_Detided_region3 %>% # complete time-series%
        ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
        geom_point(col = 'blue', size = 0.1) +
        labs(x = 'Year', 
             y = 'Detided Sea-level (m)', 
             title = 'ADCIRC Reconstruction of Detided Hourly Sea-Level at Wrightsville Beach') +
        ylim(-2.5, 2.5)

p8 <- NOAA_OBS_Detided_region3 %>% # complete time-series
        ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
        geom_point(col = 'red', size = 0.1) +
        labs(x = 'Year', y = 'Detided Sea-level (m)', title = 'Observed (NOAA) Detided Hourly Sea-Level at Wrightsville Beach') +
        ylim(-2.5, 2.5)

grid.arrange(p7, p8, ncol = 2)

grid.arrange(p7a, p8a, p7, p8, nrow = 2, ncol =2)

# box plots each station
ADC_POST_Detided_region3 %>%
  select(-TIME, -year, -month) %>%
  melt() %>%
  ggplot(aes(x = value, y = variable)) +
  geom_boxplot(outlier.size = 0.1) +
  labs(x = 'Sea-Level (m)', y = 'Station', title = 'Boxplots for Detided ADCIRC Reconstructed Sea-Level at each Location')

NOAA_OBS_Detided_region3 %>%
  select(-TIME, -year, -month) %>%
  melt() %>%
  ggplot(aes(x = value, y = variable)) +
  geom_boxplot(outlier.size = 0.1) +
  labs(x = 'Sea-Level (m)', y = 'Station', title = 'Boxplots of NOAA Detided Sea-Level Record at each Location')
```

```{r daily mean sea-level creation}
# raw data
df_mean_ADCIRC_raw <- ADC_POST_region3 %>% # compute data frame with daily mean for each station (ADCIRC)
  group_by(year, month, day) %>%
  summarise_all(mean, na.rm = T)

df_mean_NOAA_raw <- NOAA_OBS_region3 %>% # compute data frame with daily mean for each station (ADCIRC)
  group_by(year, month, day) %>%
  summarise_all(mean, na.rm = T)

# detided data
df_mean_ADCIRC <- ADC_POST_Detided_region3 %>% # compute data frame with daily mean for each station (ADCIRC)
  group_by(year, month, day) %>%
  summarise_all(mean, na.rm = T)

df_mean_NOAA <- NOAA_OBS_Detided_region3 %>% # compute data frame with daily mean for each station (ADCIRC)
  group_by(year, month, day) %>%
  summarise_all(mean, na.rm = T)
```

```{r daily mean sea-level EDA, warning = F}
p9 <- df_mean_ADCIRC %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Day', 
       y = str_wrap('Detided Daily Mean Sea-level (m)', 20), 
       title = 'ADCIRC Reconstruction of Detided Daily Mean Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

p10 <- df_mean_NOAA %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2014-02-01 00:00:00') %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Day',
       y = str_wrap('Detided Daily Mean Sea-level (m)', 20), 
       title = 'Observed (NOAA) Detided Daily Mean Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p9, p10, ncol = 2)

grid.arrange(p3a, p4a, p3, p4, p9, p10, nrow =3, ncol = 2)

p11 <- df_mean_ADCIRC %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Month', 
       y = str_wrap('Detided Daily Mean Sea-level (m)', 20), 
       title = 'ADCIRC Reconstruction of Detided Daily Mean Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

p12 <- df_mean_NOAA %>%
  filter('2014-01-01 0:00:00' <= TIME, TIME <= '2015-01-01 00:00:00') %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Month', 
       y =  str_wrap('Detided Daily Mean Sea-level (m)', 20), 
       title = 'Observed (NOAA) Detided Daily Mean Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

grid.arrange(p11, p12, ncol = 2)

grid.arrange(p5a, p6a, p5, p6, p11, p12, nrow = 3, ncol = 2)

p13 <- df_mean_ADCIRC %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Year', y = str_wrap('Detided Daily Mean Sea-level (m)', 20), title = 'ADCIRC Reconstruction of Detided Daily Mean Sea-Level at Wrightsville Beach') +
  ylim(-2.5, 2.5)

play13 <- p13 + transition_reveal(1:nrow(df_mean_ADCIRC))
animate(play13, height = 400, width = 550)
anim_save(filename = "daily-detided-mean-ADCIRC-wrighstville.gif", path ='./figures')

p14 <- df_mean_NOAA %>%
  ggplot(aes(x = TIME, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Year', y = str_wrap('Detided Daily Mean Sea-level (m)', 20), title = 'Observed (NOAA) Detided Daily Mean Sea-Level at Wrightsville Beach') + 
  ylim(-2.5, 2.5)

grid.arrange(p13, p14, ncol = 2)

grid.arrange(p7a, p8a, p7, p8, p13, p14, nrow = 3, ncol = 2)
```


```{r yearly maxima sea-level creation, message = F, warning = F}
# for examing missing valus in NOAA_OBS_Detided_region3
source('./functions/overview_na.R')
source('./functions/max_timeseries.R')

# less than or equal to 10% of data missing, logical specifies if by station of by year & station
# overview_na(NOAA_OBS_Detided_region3, 0.01, T) 

# use max_timeseries NA exclusion rule to compute yearly maxima
# test <- max_timeseries(df_mean_NOAA, 0.5)

# create data frame with yearly maxima over hourly observations for each station
# df_max <- ADC_POST_Detided_region3 %>%
#          select(-TIME, -month, -day) %>%
#         group_by(year) %>%
#        summarise_all(max, na.rm = T) %>%
#       mutate(year = as.numeric(year))

#df_max_NOAA <- NOAA_OBS_Detided_region3 %>%
#           select(-TIME, -month, -day) %>%
#           group_by(year) %>%
#           summarise_all(max, na.rm = T) %>%
#           mutate(year = as.numeric(year)) %>%
#           replace_with_na_all(~.x == -Inf)

# create data frame with yearly maxima over daily means for each station (ADCIRC)
df_max_ADCIRC <- df_mean_ADCIRC[, -(2:4)] %>%
              group_by(year) %>%
              summarise_all(max, na.rm = T) %>%
              mutate(year = as.numeric(year))
 
# create data frame with yearly maxima over daily means for each station (NOAA)
df_max_NOAA <- df_mean_NOAA[, -(2:4)] %>%
                  group_by(year) %>%
                  summarise_all(max, na.rm = T) %>%
                  mutate(year = as.numeric(year)) %>%
                  replace_with_na_all(~.x == -Inf)
```

```{r yearly maxima EDA, message = F, warning = F}
# single station (ADCIRC)
p15 <- df_max_ADCIRC %>%
  ggplot(aes(x = year, y = WrightsvilleBeach)) +
  geom_point(col = 'blue', size = 0.1) +
  labs(x = 'Year',
       y = str_wrap('Detided Daily Mean Sea-level Maximum (m)', 15), 
       title = str_wrap('ADCIRC Reconstruction of Yearly (Detided Daily Mean) Sea-Level Maxima at Wrightsville Beach', 70)) +
  ylim(-2.5, 2.5)

# single station (NOAA)
p16 <- df_max_NOAA %>%
  ggplot(aes(x = year, y = WrightsvilleBeach)) +
  geom_point(col = 'red', size = 0.1) +
  labs(x = 'Year', 
       y = str_wrap('Detided Daily Mean Sea-level Maximum (m)', 15),
       title = str_wrap('Observed (NOAA) Yearly (Detided Daily Mean) Sea-Level Maxima at Wrightsville Beach', 70)) +
  ylim(-2.5, 2.5) # 0.3, 0.7

grid.arrange(p15, p16, ncol = 2)

grid.arrange(p7a, p8a, p7, p8, p13, p14, p15, p16, nrow = 4, ncol = 2)

# test$FortPulaski%>%
# ggplot(aes(x = year, y = max)) +
# geom_point(col = 'blue') +
# labs(x = 'Year', y = 'Sea-level (m)', title = 'NOAA Observed Detided Sea-Level Maxima for Wrightsville Beach') +
# scale_x_discrete(breaks = seq(1980, 2020, by = 10))

#  time-series for maxima
df_max_ADCIRC %>%
  as.tibble() %>%
  melt(id.vars = c('year')) %>%
  ggplot(aes(x = year, y = value)) +
  geom_point(col = 'blue', size = 0.01) +
  facet_wrap(~variable) +
  labs(x = 'Year', 
       y = str_wrap('Yearly (Detided Daily Mean) Sea-level Maxima (m)', 30), 
       title = 'Time-Series for ADCIRC Reconstruction of Yearly (Detided Daily Mean) Sea-Level Maxima') +
  scale_x_continuous(breaks = c(1980, 1995, 2010)) +
  ylim(-2.5, 2.5)

df_max_NOAA %>%
  as.tibble() %>%
  melt(id.vars = c('year')) %>%
  ggplot(aes(x = year, y = value)) +
  geom_point(col = 'red', size = 0.01) +
  facet_wrap(~variable) +
  labs(x = 'Year', y = str_wrap('Yearly (Detided Daily Mean) Sea-level Maxima (m)', 30), title = 'Time-Series for Observed (NOAA) Yearly (Detided Daily Mean) Sea-Level Maxima') +
  scale_x_continuous(breaks = c(1980, 1995, 2010)) +
  ylim(-2.5, 2.5) # 0 to 2.5
  
# box plots for maxima 
df_max_ADCIRC %>%
  select(-year) %>%
  melt() %>%
  ggplot(aes(x = value, y = variable)) +
  geom_boxplot(outlier.size = 0.01, col = 'blue') +
  labs(y = 'Station',
       x = 'Yearly (Detided Daily Mean) Sea-level Maxima (m)', 
       title = 'Boxplots for ADCIRC Reconstruction of Yearly (Detided Daily Mean) Sea-Level Maxima') +
  xlim(-2.5, 2.5)

df_max_NOAA %>%
  select(-year) %>%
  melt() %>%
  ggplot(aes(x = value, y = variable)) +
  geom_boxplot(outlier.size = 0.01, col = 'red') +
  labs(y = 'Station', 
       x = 'Yearly (Detided Daily Mean) Sea-level Maxima (m)', 
       title = 'Boxplots for Observed (NOAA) Yearly (Detided Daily Mean) Sea-Level Maxima') +
  xlim(-2.5, 2.5) 
  

# density plots for maxima 
df_max_ADCIRC %>%
  as.tibble() %>%
  melt(id.vars = c('year')) %>%
  ggplot(aes(x = value)) +
  geom_density(col = 'blue') +
  facet_wrap(~variable) +
  labs(x = 'Yearly (Detided Daily Mean) Sea-level Maxima (m)', title = 'Kernal Density Estimates for ADCIRC Reconstruction of Yearly (Detided Daily Mean) Sea-Level Maxima') +
  xlim(-2.5, 2.5) +
  ylim(0, 6)

df_max_NOAA %>%
  as.tibble() %>%
  melt(id.vars = c('year')) %>%
  ggplot(aes(x = value)) +
  geom_density(col = 'red') +
  facet_wrap(~variable) +
  labs(x = 'Yearly (Detided Daily Mean) Sea-level Maxima (m)', title = 'Kernal Density Estimates for Observed (NOAA) Yearly (Detided Daily Mean) Sea-Level Maxima') +
  xlim(-2.5, 2.5) + # 0 to 1.5
  ylim(0, 6)
```
